service: ms-flask-log

provider:
  name: aws
  runtime: python3.11
  region: us-east-1

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-offline
custom:
  wsgi:
    app: src/infraestructure/handlers/lambda_hlr.handler
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  serverless-offline:
    httpPort: 5001

functions:
  lambdaLog:
    handler: wsgi_handler.handler
    timeout: 30
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
  sqsSaveLog:
    handler: src/infraestructure/handlers/sqs_hlr.save_log_handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:850978708718:LogQueue